In [1]:
import numpy as np
import pandas as pd
import datetime
import json
import geojson
import math
import matplotlib as plt
import os
import sys

# import random trajectory generator
traj_path = "/Users/jimmy.shao/GPS_traj_random_gen/"
sys.path.append(os.path.abspath(traj_path))
from GPTG import GPTG

In [2]:
# general settings
avg_v = 15 # m/s, agv speed
r = 100 # meter, pie radius, define how close is "near spot"
theta = np.pi/12 #radian, pie angle

In [3]:
# read pattern from 
from_col = ['A1', 'A5', 'B1', 'B2', 'B2a', 'B3_1', 'B3_2', 'B3_3', 'B3_4', 'B3_5', 'B3_6', 'B3_7', 'B3_8', 'B3_9', 'B3_10', 'B3_11', 'B4', 'B4a', 'B5', 'B7', 'E8a', 'E8b']
tw_taxi = pd.read_csv("tw_taxi_info.csv", usecols=from_col)
to_col = ['full_time', 'single_driver', 'travel_distance', 'off_day', 'off_day1', 'slot1', 'slot2', 'slot3', 'slot4', 'slot5', 'slot6', 'slot7', 'slot8', 'slot9', 'slot10', 'slot11', 'op_time', 'op_time1', 'no_passenger_time', 'trip', 'city', 'city1']
tw_taxi.columns = to_col
print(len(from_col))
print(len(to_col))

# accept full-time, single driver tp/ntp only
tw_taxi = tw_taxi[(tw_taxi['full_time'] == 1) & (tw_taxi['single_driver'] == 2) & (tw_taxi['city'] < 3) & (tw_taxi['city1'] < 3)]

22
22

In [4]:
# off day function
def off_day_transform(df):
    dic = {1: 0, 2:np.random.random_integers(1,2), 3:np.random.random_integers(3,4), 4:np.random.random_integers(5,6), 5:np.random.random_integers(7,8)}
    if df['off_day'] < 6:
        return dic[df['off_day']]
    else:
        return df['off_day1']
    
# operation duration function
def op_time_transform(df):
    dic = {1:np.random.uniform(0,4), 2:np.random.uniform(4,6), 3:np.random.uniform(6,8), 4:np.random.uniform(8,10), 5:np.random.uniform(10,12), 6:np.random.uniform(12,14)}
    if df['op_time'] < 7:
        return dic[df['op_time']]
    else:
        return df['op_time1']
    
# travel distance function
def travel_dist_transform(df):
    dic = {1:np.random.uniform(0,50), 2:np.random.uniform(50,100), 3:np.random.uniform(100,130), 4:np.random.uniform(130,160), 5:np.random.uniform(160,190), 6:np.random.uniform(190,220), 7:np.random.uniform(22,250), 8:np.random.uniform(250,280)}
    return dic[df['travel_distance']]

# no passenger time function
def no_passenger_time_transform(df):
    dic = {1:np.random.uniform(0,0.5), 2:np.random.uniform(0.5,1), 3:np.random.uniform(1,2), 4:np.random.uniform(2,3), 5:np.random.uniform(3,4), 6:np.random.uniform(4,5), 7:np.random.uniform(5,6), 8:np.random.uniform(6,7), 9:np.random.uniform(7,8), 10:np.random.uniform(8,9), 11:np.random.uniform(9,10), 12:np.random.uniform(10,24)}
    return dic[df['no_passenger_time']]

# daily trip function
def trip_transform(df):
    dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
    return dic[df['trip']]

# transform off day and operation duration
tw_taxi['off_day'] = tw_taxi.apply(off_day_transform, axis=1)
tw_taxi['op_time'] = tw_taxi.apply(op_time_transform, axis=1)
tw_taxi['travel_distance'] = tw_taxi['travel_distance'].fillna(np.random.random_integers(1, 8))
tw_taxi['travel_distance'] = tw_taxi.apply(travel_dist_transform, axis=1)
tw_taxi['no_passenger_time'] = tw_taxi['no_passenger_time'].fillna(np.random.random_integers(1, 12))
tw_taxi['no_passenger_time'] = tw_taxi.apply(no_passenger_time_transform, axis=1)
tw_taxi['trip'] = tw_taxi['trip'].fillna(np.random.random_integers(1, 11))
tw_taxi['trip'] = tw_taxi.apply(trip_transform, axis=1)
tw_taxi = tw_taxi.drop(columns=['off_day1', 'op_time1', 'full_time', 'single_driver', 'city', 'city1'], axis=1)
tw_taxi = tw_taxi.fillna(0)
tw_taxi

/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  dic = {1: 0, 2:np.random.random_integers(1,2), 3:np.random.random_integers(3,4), 4:np.random.random_integers(5,6), 5:np.random.random_integers(7,8)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:3: DeprecationWarning: This function is deprecated. Please call randint(3, 4 + 1) instead
  dic = {1: 0, 2:np.random.random_integers(1,2), 3:np.random.random_integers(3,4), 4:np.random.random_integers(5,6), 5:np.random.random_integers(7,8)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:3: DeprecationWarning: This function is deprecated. Please call randint(5, 6 + 1) instead
  dic = {1: 0, 2:np.random.random_integers(1,2), 3:np.random.random_integers(3,4), 4:np.random.random_integers(5,6), 5:np.random.random_integers(7,8)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:3: DeprecationWarning: This function is deprecated. Please call randint(7, 8 + 1) instead
  dic = {1: 0, 2:np.random.random_integers(1,2), 3:np.random.random_integers(3,4), 4:np.random.random_integers(5,6), 5:np.random.random_integers(7,8)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:35: DeprecationWarning: This function is deprecated. Please call randint(1, 8 + 1) instead
  tw_taxi['travel_distance'] = tw_taxi['travel_distance'].fillna(np.random.random_integers(1, 8))
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:37: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  tw_taxi['no_passenger_time'] = tw_taxi['no_passenger_time'].fillna(np.random.random_integers(1, 12))
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:39: DeprecationWarning: This function is deprecated. Please call randint(1, 11 + 1) instead
  tw_taxi['trip'] = tw_taxi['trip'].fillna(np.random.random_integers(1, 11))
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(4, 6 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(7, 9 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(10, 12 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(13, 15 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(16, 18 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(19, 21 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(22, 24 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(25, 27 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(28, 30 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}
/var/folders/91/7rfwkjr118d8hfgspxh0gly944z1vk/T/ipykernel_20495/2649683545.py:29: DeprecationWarning: This function is deprecated. Please call randint(35, 40 + 1) instead
  dic = {1: np.random.random_integers(1,3), 2:np.random.random_integers(4,6), 3:np.random.random_integers(7,9), 4:np.random.random_integers(10,12), 5:np.random.random_integers(13,15), 6:np.random.random_integers(16,18), 7:np.random.random_integers(19,21), 8:np.random.random_integers(22,24), 9:np.random.random_integers(25,27), 10:np.random.random_integers(28,30), 11:np.random.random_integers(35,40)}

,travel_distance,off_day,slot1,slot2,slot3,slot4,slot5,slot6,slot7,slot8,slot9,slot10,slot11,op_time,no_passenger_time,trip
0,66.919413,5.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.004192,0.993538,4
1,127.262500,3.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,7.635264,1.228667,6
2,48.660166,8.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.190606,0.846261,5
4,100.042873,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,8.807653,1.987495,17
5,135.505430,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,10.971068,1.548991,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8850,159.651975,3.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11.468697,3.306579,18
8855,215.991250,8.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,8.156900,0.314539,26
8856,161.149647,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.148471,0.787315,14
8857,80.086977,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,9.649436,4.284715,11
8859,179.773437,8.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,9.224895,0.134926,25

In [5]:
def total_slot(df):
    count = 0
    for i in range(1,12):
        count += df.iloc[1+i]
    return count

def trip_distribution(df):
    distribute = []
    _max = df['slot_count']
    _num = df['trip']
    if _max < 2:
        numbers = [_num]
    else:
        numbers = sorted(np.random.choice(int(_num),int(_max-1)))
    count = 0
    for i in range(1,12):
        if df['slot'+str(i)] == 0:
            distribute.append(0)
        else:
            if count == 0:
                distribute.append(numbers[0])
                count += 1
            elif count < _max-1:
                distribute.append(numbers[count] - numbers[count-1])
                count += 1
            else:
                distribute.append(int(_num - numbers[-1])) 
    # for i in range(1, int(_max-1)):
    #     distribute.append(numbers[i] - numbers[i-1])
    # distribute.append(int(_num - numbers[-1]))  
    return distribute 

tw_taxi['slot_count'] = tw_taxi.apply(total_slot, axis=1)
tw_taxi = tw_taxi.drop(tw_taxi[(tw_taxi['slot_count'] == 0) & (tw_taxi['trip'] > 0)].index)

tw_taxi['trip_distribution'] = tw_taxi.apply(trip_distribution, axis=1)
tw_taxi = tw_taxi.reset_index()
tw_taxi

,index,travel_distance,off_day,slot1,slot2,slot3,slot4,slot5,slot6,slot7,slot8,slot9,slot10,slot11,op_time,no_passenger_time,trip,slot_count,trip_distribution
0,0,66.919413,5.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.004192,0.993538,4,7.0,"[0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1]"
1,1,127.262500,3.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,7.635264,1.228667,6,3.0,"[0, 0, 3, 0, 2, 0, 1, 0, 0, 0, 0]"
2,2,48.660166,8.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.190606,0.846261,5,1.0,"[0, 0, 5.0, 0, 0, 0, 0, 0, 0, 0, 0]"
3,4,100.042873,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,8.807653,1.987495,17,2.0,"[0, 0, 0, 0, 0, 0, 0, 4, 0, 13, 0]"
4,5,135.505430,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,10.971068,1.548991,15,2.0,"[0, 0, 0, 11, 0, 0, 0, 0, 4, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3735,8850,159.651975,3.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11.468697,3.306579,18,7.0,"[0, 0, 0, 0, 1, 1, 1, 11, 2, 1, 1]"
3736,8855,215.991250,8.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,8.156900,0.314539,26,5.0,"[0, 0, 0, 14, 4, 6, 2, 0, 0, 0, 0]"
3737,8856,161.149647,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.148471,0.787315,14,4.0,"[1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 11]"
3738,8857,80.086977,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,9.649436,4.284715,11,4.0,"[0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 8]"
3739,8859,179.773437,8.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,9.224895,0.134926,25,6.0,"[0, 0, 11, 6, 3, 3, 1, 1, 0, 0, 0]"

Up to now data information:

number of drivers: 3740
number of trip: 49469

市區定義：中正 大安 松山 信義 板橋 永和 中和 中山 (60% start points, # = 2244)

一級郊區定義： 文山 新店 蘆洲 三重 新莊 萬華 南港 內湖 大同 林口 士林 (30% start points, # = 1122)

郊區定義：ELSE (10% start points, # = 374)

除外：烏來 坪林 石碇 雙溪 貢寮

<!-- ![<District Level>](./level.png = 250x250) -->
<img src="./district_level.png" width="500">

In [6]:
# trajectories creation
start_point_col = ['id', 'lon', 'lat']
downtown_start_point = pd.read_csv('./start_point/DownTown.csv', usecols=['id', 'x', 'y'])
uptown_start_point = pd.read_csv('./start_point/UpTown.csv', usecols=['id', 'x', 'y'])
country_start_point = pd.read_csv('./start_point/Country.csv', usecols=['id', 'x', 'y'])
downtown_start_point.columns = start_point_col
uptown_start_point.columns = start_point_col
country_start_point.columns = start_point_col

downtown_start_point = downtown_start_point.sample(frac=1).reset_index(drop=True).drop(columns=['id'])
uptown_start_point = uptown_start_point.sample(frac=1).reset_index(drop=True).drop(columns=['id'])
country_start_point = country_start_point.sample(frac=1).reset_index(drop=True).drop(columns=['id'])

print(downtown_start_point.head())
print(uptown_start_point.head())
print(country_start_point.head())

          lon        lat
0  121.522814  25.039140
1  121.544716  25.041320
2  121.450313  25.001076
3  121.530370  25.044925
4  121.480538  25.018891
          lon        lat
0  121.501805  25.062583
1  121.588284  25.071232
2  121.597642  25.021521
3  121.567734  25.157663
4  121.576731  24.954432
          lon        lat
0  121.785337  25.057888
1  121.616543  25.120915
2  121.557749  25.265558
3  121.765947  25.051974
4  121.771134  25.004621

In [7]:
# # randomly concat start points
# all_start_point = pd.concat([downtown_start_point, uptown_start_point, country_start_point], axis=0, ignore_index=True)
# all_start_point = all_start_point.sample(frac=1).reset_index(drop=True)
# all_start_point = all_start_point.drop(columns=['id'], axis=1)
# print(all_start_point)
# taxi_start = pd.concat([tw_taxi, all_start_point], axis=1)
# taxi_start

In [8]:
sorted_tw_taxi = tw_taxi.sort_values(by=['trip'])
country_tw_taxi = sorted_tw_taxi.iloc[:374, :]
uptown_tw_taxi = sorted_tw_taxi.iloc[375:1496, :]
downtown_tw_taxi = sorted_tw_taxi.iloc[1497:, :]

In [9]:
start_date = datetime.datetime(111,1,1,0,0,0)
# day_count = 30
# for i in range(day_count):
#     start_date += datetime.timedelta(days=1)
    
hr_slot = [0,4,6,8,10,12,14,16,18,20,22,24]
    
start_hr = [np.nonzero(x)[0][0] for x in tw_taxi['trip_distribution'].tolist()]
start_timestamp = [start_date + datetime.timedelta(hours=np.random.uniform(hr_slot[i],  hr_slot[i+1])) for i in start_hr]

# exact_start_time = start_date + datetime.timedelta(hours=np.random.uniform(hr_slot[i], hr_slot[i+1]))


# start_list = all_start_point.values.tolist()
# print(start_list)



# def traj_gen(df, start_date):
#     # general settings
#     avg_v = 15 # m/s, agv speed
#     r = 100 # meter, pie radius, define how close is "near spot"
#     theta = np.pi/12 #radian, pie angle
#     start_point = [df['lon'], df['lat']]
#     ang = np.random.uniform(0, 2*np.pi)
#     vec = [math.cos(ang), math.sin(ang)]
#     time = 0
#     generator = GPTG(avg_v, r, theta, start_point, vec)
#     if df['trip_distribution'][0] > 0:
#         time = df['slot_count']* 2 + 2
#     else:
#         time = df['slot_count'] * 2

In [10]:
def traj_gen(df1, df2):
    def traj_gen_per_day(coordinate, duration, _start_time):
        # general settings
        avg_v = 15 # m/s, agv speed
        r = 100 # meter, pie radius, define how close is "near spot"
        theta = np.pi/12 #radian, pie angle
        vec_list = []
        for i in range(len(coordinate)):
            ang = np.random.uniform(0, 2*np.pi)
            vec = [math.cos(ang), math.sin(ang)]
            vec_list.append(vec)
        generator = GPTG(avg_v, r, theta, coordinate, vec_list)
        generator.create_trajectory_by_time(time=duration, start_time=_start_time)
        return generator
        
    start_date = datetime.datetime(111,1,1,0,0,0)
    hr_slot = [0,4,6,8,10,12,14,16,18,20,22,24]
    start_hr = [np.nonzero(x)[0][0]  for x in df1['trip_distribution'].tolist()]
    end_hr =   [np.nonzero(x)[0][-1] for x in df1['trip_distribution'].tolist()]
    day_count = 31
    month_list = []
    for day in range(day_count):
        exact_start_date = start_date + datetime.timedelta(days=day)
        start_timestamp = [exact_start_date + datetime.timedelta(hours=np.random.uniform(hr_slot[i],  hr_slot[i+1])) for i in start_hr]
        end_timestamp = [exact_start_date + datetime.timedelta(hours=hr_slot[i+1]) for i in end_hr]
        duration = [(m-n).total_seconds() for m, n in zip(end_timestamp, start_timestamp)]
        start_point = df2.sample(frac=1).values.tolist()
        month_list.append(traj_gen_per_day(start_point, duration, start_timestamp))
        
    return month_list

In [ ]:
country_traj = traj_gen(downtown_tw_taxi, downtown_start_point)
country_traj

In [ ]:
uptown_traj = traj_gen(uptown_tw_taxi, uptown_start_point)
uptown_traj

In [ ]:
downtown_traj = traj_gen(downtown_tw_taxi, downtown_start_point)
downtown_traj